Traceback (most recent call last):
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/khanh/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/khanh/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df['tax'].plot()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_76175/2147348016.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m[0;34m[[0m[0;34m'tax'[0m[0;34m][0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/miniconda3/lib/python3.9/site-packages/pandas/plotting/_core.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    890[0m [0;34m[0m[0m
[1;32m    891[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 892[0;31m         [0mplot_backend[0m [0;34m=[0m [0m_get_plot_backend[0m[0;34m([0m[0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0;34m"backend"[0m[0;34m,[0m [0;32mNone[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    893[0m [0;34m[0m[0m
[1;32m    894[0m         x, y, kind, kwargs = self._get_call_args(

[0;32m~/miniconda3/lib/python3.9/site-packages/pandas/plotting/_core.py[0m in [0;36m_get_plot_backend[0;34m(backend)[0m
[1;32m   1812[0m         [0;32mreturn[0m [0m_backends[0m[0;34m[[0m[0mbackend[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1813[0m [0;34m[0m[0m
[0;32m-> 1814[0;31m     [0mmodule[0m [0;34m=[0m [0m_load_backend[0m[0;34m([0m[0mbackend[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1815[0m     [0m_backends[0m[0;34m[[0m[0mbackend[0m[0;34m][0m [0;34m=[0m [0mmodule[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1816[0m     [0;32mreturn[0m [0mmodule[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/lib/python3.9/site-packages/pandas/plotting/_core.py[0m in [0;36m_load_backend[0;34m(backend)[0m
[1;32m   1752[0m             [0mmodule[0m [0;34m=[0m [0mimportlib[0m[0;34m.[0m[0mimport_module[0m[0;34m([0m[0;34m"pandas.plotting._matplotlib"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1753[0m         [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1754[0;31m             raise ImportError(
[0m[1;32m   1755[0m                 [0;34m"matplotlib is required for plotting when the "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1756[0m                 [0;34m'default backend "matplotlib" is selected.'[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: matplotlib is required for plotting when the default backend "matplotlib" is selected.
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

